language: python
python :
    - "3.6"
addons:
  apt:
    sources:
        - http://neuro.debian.net/lists/xenial.us-ca.full
    packages:
      -  singularity-container
script:
    - singularity build appian.simg APPIAN/Singularity
    - singularity exec appian.simg bash -c "hello, world!"



