language: python
python :
    - "3.6"
addons:
  apt:
    sources:
    packages:
      -  singularity-container
script:
    - singularity build appian.simg APPIAN/Singularity
    - singularity exec appian.simg bash -c "hello, world!"



