language: python
python :
    - "3.6"
before_install:
    - sudo wget -O- http://neuro.debian.net/lists/xenial.us-ca.full | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
    - sudo apt-key adv --recv-keys --keyserver hkp://pool.sks-keyservers.net:80 0xA5D32F012649A5A9
    - sudo apt-get update -q
    - sudo apt-get install -y singularity-container
before_script :
    - ls 
    - pwd
    - find / -name Singularity | grep APPIAN
    - #sudo singularity build /opt/appian.simg `find / -name Singularity`
script:
    - pwd
    - ls
    - singularity exec /opt/appian.simg bash -c "hello, world!"



